name: CreativeOlympics
main: creativeolympics.Main
version: 1.0
description: Creative Olympics Plugin

commands:
  updatewhitelist:
    description: Updates the white list
    usage: /updatewhitelist
  updateblacklist:
    description: Updates the bans list
    usage: /updateblacklist